// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uvliviaazywkluhpyawk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bGl2aWFhenl3a2x1aHB5YXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNjg5MTEsImV4cCI6MjA3Njc0NDkxMX0.sxe9ZDcI4qijH6Y4b8bM-ctWTg4LgVk2I9aLEGzJ2Qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);